import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [count, setCount] = useState(0);

  // console.log("rendered");

  useEffect(() => {
    // setData(Math.random());
    // document.getElementById("random").innerText = `${Math.random()}`;
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        {/* <div>{Math.random()}</div> */}
        {/* <div>{data}</div> */}
        <div id="random"></div>
        <h1>{count}</h1>
        <button onClick={() => setCount((prev) => prev + 1)}>click</button>
        <Link href="/jsons/1" passHref={true}>
          <h1>Go to Json</h1>
        </Link>
        {/* next는 해당 페이지에서 연결된 path(next/link)들에 넘겨줄 props 들을 JSON 으로 미리 받아온다 */}
        {/* ( JSON은 getStaticProps를 사용한 페이지 생성시 같이 생성된다 ) */}
        {/* Link나 Router를 통해 navigate 할 때는 미리 받아온 JSON들을 이용하여 client-side rendering 한다 */}
        {/* CSR?? 그럼 SEO는..? 아마 검색엔진은 Link를 직접 눌러 navigate하는 것과는 다른 방식인 것으로 추정.. */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
